4.1 task 1

In [ ]:
def convert_length(value, from_unit):
    """
    Converts length between meters and feet.
    :param value: Numeric value to convert
    :param from_unit: 'm' for meters to feet, 'ft' for feet to meters
    :return: Converted value
    """
    conversion_factor = 3.28084
    if from_unit == 'm':
        return value * conversion_factor
    elif from_unit == 'ft':
        return value / conversion_factor
    else:
        raise ValueError("Unsupported length unit")

def convert_weight(value, from_unit):
    """
    Converts weight between kilograms and pounds.
    :param value: Numeric value to convert
    :param from_unit: 'kg' for kilograms to pounds, 'lbs' for pounds to kilograms
    :return: Converted value
    """
    conversion_factor = 2.20462
    if from_unit == 'kg':
        return value * conversion_factor
    elif from_unit == 'lbs':
        return value / conversion_factor
    else:
        raise ValueError("Unsupported weight unit")

def convert_volume(value, from_unit):
    """
    Converts volume between liters and gallons.
    :param value: Numeric value to convert
    :param from_unit: 'L' for liters to gallons, 'gal' for gallons to liters
    :return: Converted value
    """
    conversion_factor = 0.264172
    if from_unit == 'L':
        return value * conversion_factor
    elif from_unit == 'gal':
        return value / conversion_factor
    else:
        raise ValueError("Unsupported volume unit")

def main():
    try:
        print("Choose conversion type:")
        print("1. Length (m <-> ft)")
        print("2. Weight (kg <-> lbs)")
        print("3. Volume (L <-> gal)")

        choice = input("Enter choice (1/2/3): ")
        value = float(input("Enter value to convert: "))

        if choice == '1':
            unit = input("Enter unit ('m' for meters, 'ft' for feet): ")
            result = convert_length(value, unit)
            print("Converted value:", result)
        elif choice == '2':
            unit = input("Enter unit ('kg' for kilograms, 'lbs' for pounds): ")
            result = convert_weight(value, unit)
            print("Converted value:", result)
        elif choice == '3':
            unit = input("Enter unit ('L' for liters, 'gal' for gallons): ")
            result = convert_volume(value, unit)
            print("Converted value:", result)
        else:
            print("Invalid choice.")
    except ValueError as e:
        print("Error:", e)
    except Exception as e:
        print("Unexpected error:", e)

if __name__ == "__main__":
    main()


Choose conversion type:
1. Length (m <-> ft)
2. Weight (kg <-> lbs)
3. Volume (L <-> gal)
Enter choice (1/2/3): 2
Enter value to convert: 4
Enter unit ('kg' for kilograms, 'lbs' for pounds): kg
Converted value: 8.81848


4.1 task 2


In [ ]:
def calculate_sum(numbers):
    """
    Calculates the sum of a list of numbers.
    :param numbers: List of numeric values
    :return: Sum of numbers
    """
    return sum(numbers)

def calculate_average(numbers):
    """
    Calculates the average of a list of numbers.
    :param numbers: List of numeric values
    :return: Average of numbers
    """
    return sum(numbers) / len(numbers) if numbers else 0

def find_maximum(numbers):
    """
    Finds the maximum number in a list.
    :param numbers: List of numeric values
    :return: Maximum value
    """
    return max(numbers)

def find_minimum(numbers):
    """
    Finds the minimum number in a list.
    :param numbers: List of numeric values
    :return: Minimum value
    """
    return min(numbers)

def main():
    try:
        print("Choose an operation:")
        print("1. Sum")
        print("2. Average")
        print("3. Maximum")
        print("4. Minimum")

        choice = input("Enter choice (1/2/3/4): ")
        numbers = list(map(float, input("Enter numbers separated by spaces: ").split()))

        if not numbers:
            raise ValueError("The list of numbers cannot be empty.")

        if choice == '1':
            print("Sum:", calculate_sum(numbers))
        elif choice == '2':
            print("Average:", calculate_average(numbers))
        elif choice == '3':
            print("Maximum:", find_maximum(numbers))
        elif choice == '4':
            print("Minimum:", find_minimum(numbers))
        else:
            print("Invalid choice.")
    except ValueError as e:
        print("Error:", e)
    except Exception as e:
        print("Unexpected error:", e)

if __name__ == "__main__":
    main()



Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter choice (1/2/3/4): 3
Enter numbers separated by spaces: 7 9
Maximum: 9.0


4.2

In [ ]:
def extract_every_other(lst):
    """
    Extracts every other element from the list, starting from the first element.
    :param lst: List of elements
    :return: List with every other element
    """
    return lst[::2]

def get_sublist(lst, start, end):
    """
    Returns a sublist from the start index to the end index (inclusive).
    :param lst: List of elements
    :param start: Starting index
    :param end: Ending index (inclusive)
    :return: Sublist from start to end index
    """
    return lst[start:end+1]

def reverse_list(lst):
    """
    Reverses the list using slicing.
    :param lst: List of elements
    :return: Reversed list
    """
    return lst[::-1]

def remove_first_last(lst):
    """
    Removes the first and last elements of the list.
    :param lst: List of elements
    :return: List without first and last elements
    """
    return lst[1:-1]

def get_first_n(lst, n):
    """
    Extracts the first n elements from the list.
    :param lst: List of elements
    :param n: Number of elements to extract
    :return: List with first n elements
    """
    return lst[:n]

def get_last_n(lst, n):
    """
    Extracts the last n elements from the list.
    :param lst: List of elements
    :param n: Number of elements to extract
    :return: List with last n elements
    """
    return lst[-n:]

def reverse_skip(lst):
    """
    Extracts elements in reverse order, starting from the second-to-last and skipping one in between.
    :param lst: List of elements
    :return: List of elements in reverse order with a skip
    """
    return lst[-2::-2]

def main():
    sample_list = [1, 2, 3, 4, 5, 6]
    print("Every other element:", extract_every_other(sample_list))
    print("Sublist (2 to 4):", get_sublist(sample_list, 2, 4))
    print("Reversed list:", reverse_list(sample_list))
    print("Without first and last:", remove_first_last(sample_list))
    print("First 3 elements:", get_first_n(sample_list, 3))
    print("Last 2 elements:", get_last_n(sample_list, 2))
    print("Reverse skip:", reverse_skip(sample_list))

if __name__ == "__main__":
    main()


Every other element: [1, 3, 5]
Sublist (2 to 4): [3, 4, 5]
Reversed list: [6, 5, 4, 3, 2, 1]
Without first and last: [2, 3, 4, 5]
First 3 elements: [1, 2, 3]
Last 2 elements: [5, 6]
Reverse skip: [5, 3, 1]


4.3

In [ ]:
def flatten(lst):
    """Flattens a nested list into a single list."""
    flat_list = []
    for sublist in lst:
        if isinstance(sublist, list):
            flat_list.extend(flatten(sublist))
        else:
            flat_list.append(sublist)
    return flat_list

def access_nested_element(lst, indices):
    """Extracts a specific element from a nested list given its indices."""
    element = lst
    for index in indices:
        element = element[index]
    return element

def sum_nested(lst):
    """Calculates the sum of all the numbers in a nested list."""
    return sum(flatten(lst))

def remove_element(lst, elem):
    """Removes all occurrences of a specific element from a nested list."""
    if isinstance(lst, list):
        return [remove_element(sublist, elem) for sublist in lst if sublist != elem]
    return lst

def find_max(lst):
    """Finds the maximum element in a nested list."""
    return max(flatten(lst))

def count_occurrences(lst, elem):
    """Counts how many times a specific element appears in a nested list."""
    return flatten(lst).count(elem)

def deep_flatten(lst):
    """Flattens a deeply nested list into a single list."""
    return flatten(lst)

def average_nested(lst):
    """Calculates the average of all elements in a nested list."""
    flat_list = flatten(lst)
    return sum(flat_list) / len(flat_list) if flat_list else 0

def main():
    nested_list = [[1, 2], [3, [4, 5]], 6]
    print("Flattened List:", flatten(nested_list))
    print("Access Nested Element (1,2):", access_nested_element([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1, 2]))
    print("Sum of Nested List:", sum_nested(nested_list))
    print("Remove Element 2:", remove_element([[1, 2], [3, 2], [4, 5]], 2))
    print("Max in Nested List:", find_max(nested_list))
    print("Count Occurrences of 2:", count_occurrences([[1, 2], [2, 3], [2, 4]], 2))
    print("Deep Flattened List:", deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))
    print("Average of Nested List:", average_nested([[1, 2], [3, 4], [5, 6]]))

if __name__ == "__main__":
    main()

Flattened List: [1, 2, 3, 4, 5, 6]
Access Nested Element (1,2): 6
Sum of Nested List: 21
Remove Element 2: [[1], [3], [4, 5]]
Max in Nested List: 6
Count Occurrences of 2: 3
Deep Flattened List: [1, 2, 3, 4, 5, 6, 7, 8]
Average of Nested List: 3.5


10.1

In [ ]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Empty Array:\n", empty_array)

# 2. Initialize an all-ones array with size 4x2
ones_array = np.ones((4, 2))
print("\nAll Ones Array:\n", ones_array)

# 3. Return a new array of given shape and type, filled with fill value
fill_value = 7  # Example fill value
filled_array = np.full((3, 3), fill_value)
print("\nFilled Array:\n", filled_array)

# 4. Return a new array of zeros with the same shape and type as a given array
reference_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(reference_array)
print("\nZeros Like Array:\n", zeros_like_array)

# 5. Return a new array of ones with the same shape and type as a given array
ones_like_array = np.ones_like(reference_array)
print("\nOnes Like Array:\n", ones_like_array)

# 6. Convert an existing list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted NumPy Array:\n", numpy_array)


Empty Array:
 [[2.72901300e-316 0.00000000e+000]
 [0.00000000e+000 6.62890265e-310]]

All Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Filled Array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Like Array:
 [[0 0 0]
 [0 0 0]]

Ones Like Array:
 [[1 1 1]
 [1 1 1]]

Converted NumPy Array:
 [1 2 3 4]


10.2

In [ ]:
import numpy as np

def flatten(lst):
    """Flattens a nested list into a single list."""
    flat_list = []
    for sublist in lst:
        if isinstance(sublist, list):
            flat_list.extend(flatten(sublist))
        else:
            flat_list.append(sublist)
    return flat_list

def access_nested_element(lst, indices):
    """Extracts a specific element from a nested list given its indices."""
    element = lst
    for index in indices:
        element = element[index]
    return element

def sum_nested(lst):
    """Calculates the sum of all the numbers in a nested list."""
    return sum(flatten(lst))

def remove_element(lst, elem):
    """Removes all occurrences of a specific element from a nested list."""
    if isinstance(lst, list):
        return [remove_element(sublist, elem) for sublist in lst if sublist != elem]
    return lst

def find_max(lst):
    """Finds the maximum element in a nested list."""
    return max(flatten(lst))

def count_occurrences(lst, elem):
    """Counts how many times a specific element appears in a nested list."""
    return flatten(lst).count(elem)

def deep_flatten(lst):
    """Flattens a deeply nested list into a single list."""
    return flatten(lst)

def average_nested(lst):
    """Calculates the average of all elements in a nested list."""
    flat_list = flatten(lst)
    return sum(flat_list) / len(flat_list) if flat_list else 0

def array_manipulation():
    """Performs various array manipulations using NumPy."""
    arr1 = np.arange(10, 50)
    matrix_3x3 = np.arange(9).reshape(3, 3)
    identity_matrix = np.eye(3)
    random_array = np.random.random(30)
    mean_value = random_array.mean()
    array_10x10 = np.random.random((10, 10))
    min_value, max_value = array_10x10.min(), array_10x10.max()
    zero_array = np.zeros(10)
    zero_array[4] = 1
    reversed_arr = np.array([1, 2, 0, 0, 4, 0])[::-1]
    border_array = np.ones((5, 5))
    border_array[1:-1, 1:-1] = 0
    checkerboard = np.zeros((8, 8))
    checkerboard[1::2, ::2] = 1
    checkerboard[::2, 1::2] = 1

    print("Array with values from 10 to 49:", arr1)
    print("3x3 Matrix:", matrix_3x3)
    print("Identity Matrix:", identity_matrix)
    print("Mean of random array:", mean_value)
    print("Min and Max of 10x10 array:", min_value, max_value)
    print("Zero array with 5th element as 1:", zero_array)
    print("Reversed array:", reversed_arr)
    print("2D array with border 1 and inside 0:", border_array)
    print("Checkerboard pattern:", checkerboard)

def main():
    nested_list = [[1, 2], [3, [4, 5]], 6]
    print("Flattened List:", flatten(nested_list))
    print("Access Nested Element (1,2):", access_nested_element([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1, 2]))
    print("Sum of Nested List:", sum_nested(nested_list))
    print("Remove Element 2:", remove_element([[1, 2], [3, 2], [4, 5]], 2))
    print("Max in Nested List:", find_max(nested_list))
    print("Count Occurrences of 2:", count_occurrences([[1, 2], [2, 3], [2, 4]], 2))
    print("Deep Flattened List:", deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))
    print("Average of Nested List:", average_nested([[1, 2], [3, 4], [5, 6]]))
    array_manipulation()

if __name__ == "__main__":
    main()

Flattened List: [1, 2, 3, 4, 5, 6]
Access Nested Element (1,2): 6
Sum of Nested List: 21
Remove Element 2: [[1], [3], [4, 5]]
Max in Nested List: 6
Count Occurrences of 2: 3
Deep Flattened List: [1, 2, 3, 4, 5, 6, 7, 8]
Average of Nested List: 3.5
Array with values from 10 to 49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
3x3 Matrix: [[0 1 2]
 [3 4 5]
 [6 7 8]]
Identity Matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Mean of random array: 0.47183655014989206
Min and Max of 10x10 array: 0.026103040857397897 0.9866972934502801
Zero array with 5th element as 1: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Reversed array: [0 4 0 0 2 1]
2D array with border 1 and inside 0: [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
Checkerboard pattern: [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 

10.3

In [ ]:
import numpy as np

def flatten(lst):
    """Flattens a nested list into a single list."""
    flat_list = []
    for sublist in lst:
        if isinstance(sublist, list):
            flat_list.extend(flatten(sublist))
        else:
            flat_list.append(sublist)
    return flat_list

def access_nested_element(lst, indices):
    """Extracts a specific element from a nested list given its indices."""
    element = lst
    for index in indices:
        element = element[index]
    return element

def sum_nested(lst):
    """Calculates the sum of all the numbers in a nested list."""
    return sum(flatten(lst))

def remove_element(lst, elem):
    """Removes all occurrences of a specific element from a nested list."""
    if isinstance(lst, list):
        return [remove_element(sublist, elem) for sublist in lst if sublist != elem]
    return lst

def find_max(lst):
    """Finds the maximum element in a nested list."""
    return max(flatten(lst))

def count_occurrences(lst, elem):
    """Counts how many times a specific element appears in a nested list."""
    return flatten(lst).count(elem)

def deep_flatten(lst):
    """Flattens a deeply nested list into a single list."""
    return flatten(lst)

def average_nested(lst):
    """Calculates the average of all elements in a nested list."""
    flat_list = flatten(lst)
    return sum(flat_list) / len(flat_list) if flat_list else 0

def array_manipulation():
    """Performs various array manipulations using NumPy."""
    arr1 = np.arange(10, 50)
    matrix_3x3 = np.arange(9).reshape(3, 3)
    identity_matrix = np.eye(3)
    random_array = np.random.random(30)
    mean_value = random_array.mean()
    array_10x10 = np.random.random((10, 10))
    min_value, max_value = array_10x10.min(), array_10x10.max()
    zero_array = np.zeros(10)
    zero_array[4] = 1
    reversed_arr = np.array([1, 2, 0, 0, 4, 0])[::-1]
    border_array = np.ones((5, 5))
    border_array[1:-1, 1:-1] = 0
    checkerboard = np.zeros((8, 8))
    checkerboard[1::2, ::2] = 1
    checkerboard[::2, 1::2] = 1

    x = np.array([[1,2],[3,5]])
    y = np.array([[5,6],[7,8]])
    v = np.array([9,10])
    w = np.array([11,12])

    print("Array with values from 10 to 49:", arr1)
    print("3x3 Matrix:", matrix_3x3)
    print("Identity Matrix:", identity_matrix)
    print("Mean of random array:", mean_value)
    print("Min and Max of 10x10 array:", min_value, max_value)
    print("Zero array with 5th element as 1:", zero_array)
    print("Reversed array:", reversed_arr)
    print("2D array with border 1 and inside 0:", border_array)
    print("Checkerboard pattern:", checkerboard)

    print("Addition of x and y:", x + y)
    print("Subtraction of x and y:", x - y)
    print("Multiplication of x by 2:", x * 2)
    print("Square of elements in x:", np.square(x))
    print("Dot product of v and w:", np.dot(v, w))
    print("Dot product of x and v:", np.dot(x, v))
    print("Dot product of x and y:", np.dot(x, y))
    print("Concatenation of x and y along rows:", np.concatenate((x, y), axis=0))
    print("Concatenation of v and w along columns:", np.column_stack((v, w)))

    try:
        print("Concatenation of x and v:", np.concatenate((x, v), axis=0))
    except ValueError as e:
        print("Error:", e)
        print("Explanation: x is a 2x2 matrix, while v is a 1D array with a shape of (2,). This causes a shape mismatch and prevents concatenation along the row axis.")

def main():
    nested_list = [[1, 2], [3, [4, 5]], 6]
    print("Flattened List:", flatten(nested_list))
    print("Access Nested Element (1,2):", access_nested_element([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1, 2]))
    print("Sum of Nested List:", sum_nested(nested_list))
    print("Remove Element 2:", remove_element([[1, 2], [3, 2], [4, 5]], 2))
    print("Max in Nested List:", find_max(nested_list))
    print("Count Occurrences of 2:", count_occurrences([[1, 2], [2, 3], [2, 4]], 2))
    print("Deep Flattened List:", deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))
    print("Average of Nested List:", average_nested([[1, 2], [3, 4], [5, 6]]))
    array_manipulation()

if __name__ == "__main__":
    main()

Flattened List: [1, 2, 3, 4, 5, 6]
Access Nested Element (1,2): 6
Sum of Nested List: 21
Remove Element 2: [[1], [3], [4, 5]]
Max in Nested List: 6
Count Occurrences of 2: 3
Deep Flattened List: [1, 2, 3, 4, 5, 6, 7, 8]
Average of Nested List: 3.5
Array with values from 10 to 49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
3x3 Matrix: [[0 1 2]
 [3 4 5]
 [6 7 8]]
Identity Matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Mean of random array: 0.45518568172442203
Min and Max of 10x10 array: 0.015093598490539706 0.9971007226736637
Zero array with 5th element as 1: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Reversed array: [0 4 0 0 2 1]
2D array with border 1 and inside 0: [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
Checkerboard pattern: [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 

10.4

In [ ]:
import numpy as np

# 1. Prove A * A_inv = I
A = np.array([[3, 4], [7, 8]])
A_inv = np.linalg.inv(A)

# Identity matrix
I = np.dot(A, A_inv)

print("1. Prove A * A_inv = I (Identity matrix):")
print("A * A_inv = \n", I)

# 2. Prove AB != BA
B = np.array([[5, 3], [2, 1]])

# Compute AB and BA
AB = np.dot(A, B)
BA = np.dot(B, A)

print("\n2. Prove AB != BA:")
print("AB = \n", AB)
print("BA = \n", BA)

# Check if AB equals BA
print("Is AB equal to BA?", np.array_equal(AB, BA))

# 3. Prove (AB)^T = B^T @ A^T
AB_T = np.transpose(AB)
B_T_A_T = np.dot(np.transpose(B), np.transpose(A))

print("\n3. Prove (AB)^T = B^T @ A^T:")
print("Transpose of AB = \n", AB_T)
print("B.T @ A.T = \n", B_T_A_T)

# Check if (AB)^T equals B.T @ A.T
print("Is (AB)^T equal to B.T @ A.T?", np.array_equal(AB_T, B_T_A_T))

# 4. Solve the system of linear equations using Inverse Method
# The system of equations is: 2x - 3y + z = -1, x - y + 2z = -3, 3x + y - z = 9
# Represent this system in matrix form: AX = B
A_system = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_system = np.array([[-1], [-3], [9]])

# Solve for X using the inverse method: X = A_inv * B
A_inv_system = np.linalg.inv(A_system)
X_system = np.dot(A_inv_system, B_system)

print("\n4. Solve the system using Inverse Method:")
print("Solution for x, y, z: \n", X_system)

# 5. Solve the system using np.linalg.solve function
X_direct = np.linalg.solve(A_system, B_system)

print("\n5. Solve the system using np.linalg.solve:")
print("Direct solution for x, y, z: \n", X_direct)


1. Prove A * A_inv = I (Identity matrix):
A * A_inv = 
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

2. Prove AB != BA:
AB = 
 [[23 13]
 [51 29]]
BA = 
 [[36 44]
 [13 16]]
Is AB equal to BA? False

3. Prove (AB)^T = B^T @ A^T:
Transpose of AB = 
 [[23 51]
 [13 29]]
B.T @ A.T = 
 [[23 51]
 [13 29]]
Is (AB)^T equal to B.T @ A.T? True

4. Solve the system using Inverse Method:
Solution for x, y, z: 
 [[ 2.]
 [ 1.]
 [-2.]]

5. Solve the system using np.linalg.solve:
Direct solution for x, y, z: 
 [[ 2.]
 [ 1.]
 [-2.]]
